[package]
name = "adobe_hosts_blocker"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["user", "process"] }
reqwest = { version = "0.12", features = ["blocking"] }
tempfile = "3.24.0"
